### PR TITLE
Fix unix socket on Mac / embedded library in Xcode. Fixes #68.

### LINKED ISSUE #68: EXC_BAD_ACCESS connecting to a unix socket on MacOS
I am getting  EXC_BAD_ACCESS trying to connect to a unix socket on MacOS 10.12.4 and IBM-Swift/BlueSocket 0.12.46.

 If I change this to be a TCP socket it works just fine.

    self.clientSocket = try Socket.create(family: Socket.ProtocolFamily.unix, type: Socket.SocketType.stream, proto: Socket.SocketProtocol.unix)
    print("Connecting to server")
    try self.clientSocket?.connect(to: "/tmp/observer_collector") // crashes with EXC_BAD_ACCESS

When this happens, I see nothing on the file system at the /tmp/observer_collector, despite executing code that should create the socket with the following code (which does not crash and does not raise any exceptions):

    self.serverSocket = try Socket.create(family: Socket.ProtocolFamily.unix, type: Socket.SocketType.stream, proto: Socket.SocketProtocol.unix)
    try self.serverSocket.listen(on: "/tmp/observer_collector")

I'm not sure if the socket got created successfully or not, since I cannot see it on the file system.  Regardless, I don't think the client connection code should crash.

Here's the stack trace:

```
Thread 3Queue : com.apple.root.background-qos (concurrent)
#0	0x000000010012470a in Socket.Signature.init(socketType : Socket.SocketType, proto : Socket.SocketProtocol, path : String?) throws -> Socket.Signature? [inlined] ()
#1	0x00000001001246f7 in specialized Socket.connect(to : String) throws -> () at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Carthage/Checkouts/BlueSocket/Sources/Socket.swift:1866
#2	0x00000001000134e7 in SocketClient.(start() -> Bool).(closure #1) at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Observer/SocketClient.swift:27
#3	0x0000000100002247 in thunk ()
#4	0x0000000100c47cfe in _dispatch_call_block_and_release ()
#5	0x0000000100c3e78c in _dispatch_client_callout ()
#6	0x0000000100c40cc1 in _dispatch_root_queue_drain ()
#7	0x0000000100c4071d in _dispatch_worker_thread3 ()
#8	0x0000000100cb5812 in _pthread_wqthread ()
#9	0x0000000100cb52ed in start_wqthread ()
Enqueued from com.apple.main-thread (Thread 1)Queue : com.apple.main-thread (serial)
#0	0x0000000100c544ca in _dispatch_queue_push ()
#1	0x00000001008e474b in DispatchQueue.async(group : DispatchGroup?, qos : DispatchQoS, flags : DispatchWorkItemFlags, execute : @convention(block) () -> ()) -> () ()
#2	0x00000001000130aa in SocketClient.start() -> Bool at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Observer/SocketClient.swift:60
#3	0x000000010000b4d7 in ViewController.viewDidAppear() -> () at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Observer/ViewController.swift:51
#4	0x000000010000b5e2 in @objc ViewController.viewDidAppear() -> () ()
#5	0x00007fffcbe19634 in -[NSViewController _sendViewDidAppear] ()
#6	0x00007fffcbe1932b in -[NSView(NSInternal) _windowDidOrderOnScreen] ()
#7	0x00007fffcbe193de in -[NSView(NSInternal) _windowDidOrderOnScreen] ()
#8	0x00007fffcc57daa8 in -[NSWindow _reallyDoOrderWindowAboveOrBelow:relativeTo:findKey:forCounter:force:isModal:] ()
#9	0x00007fffcbe15a9e in -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] ()
#10	0x00007fffcbe15633 in -[NSWindow orderWindow:relativeTo:] ()
#11	0x00007fffcbec7f7b in -[NSWindow makeKeyAndOrderFront:] ()
#12	0x00007fffd3c94519 in -[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:] ()
#13	0x00007fffcbec7107 in -[NSWindowController showWindow:] ()
#14	0x00007fffcbc9a0fe in NSApplicationMain ()
#15	0x00000001000093dc in main at /Users/dyoung/workspace/wireless-registry/macos-observer/Observer/Observer/main.swift:24
#16	0x00007fffe3941235 in start ()
```

And here is a screenshot of XCode:

screen shot 2017-05-25 at 12 28 53 pm

### PR DESCRIPTION
**Pull request by mna**
Fixes `EXC_BAD_ACCESS` for UNIX socket protocol on Mac.

## Description

In `Signature.init?(socketType:proto:path)`, the copying of the bytes from the provided path to the `sockaddr_un.sun_path` C struct field was done using `strncpy` on a pointer returned by `withCString`. For some reason, while this worked fine in `BlueSocket` tests, this fails with `EXC_BAD_ACCESS` on return of that method when called from an Xcode project using BlueSocket as embedded binary on Mac.

Copying the bytes using `UnsafeMutableBufferPointer` to wrap the `sockaddr_un.sun_path` field fixes the issue.

## Motivation and Context
See #68 

## How Has This Been Tested?

Since there were already UNIX Socket tests in BlueSocket and those were passing fine on my Macbook Pro (macOS 10.12.5), I created a separate minimal Xcode project that calls BlueSocket as Embedded Framework. This does reproduce the issue and the fix, though is not as convenient to prevent regressions in the future.

See https://github.com/mna/BlueSocketUnixSocketTest

All other tests still pass via `swift test`.

## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA) (just sent)
- [x] If applicable, I have updated the documentation accordingly. (N/A)
- [x] If applicable, I have added tests to cover my changes. (See above)

### CODE REVIEW

**Comment by mna** [comment]
Couple things to note:

* There was a lot of trailing whitespace in the source, my editor is configured to remove them so the diff is big because of this. The actual change is small, I'll comment where it is, but I think it's better to remove that unnecessary whitespace, let me know if that's fine for you.
* In addition to the fix, I unwrapped the `path` optional in an early guard to prevent having so many force-unwraps (`path!`) in the rest of the constructor.
* I did not, however, change the fact that `path` is an optional argument (not sure why) and the fact that the constructor is an optional constructor (it never returns nil).

As for the fix itself, I have no clue why the `String.withCString` paired with `strncpy` to the `sockaddr_un.sun_path` field were causing the `EXC_BAD_ACCESS`, and there may be more effective ways to fix it than the for-loop and copying each byte of the path to the `UnsafeMutableBufferPointer`, but I'm not super familiar with the Swift-C interop.

It does, however, fix the issue, and the path has a limited length anyway (quite short in fact), so that can't be too bad.

File: Sources/Socket.swift [hunk 1]
```diff
@@ -505,66 +505,62 @@ public class Socket: SocketReader, SocketWriter {
 		/// - Returns: New Signature instance
 		///
 		public init?(socketType: SocketType, proto: SocketProtocol, path: String?) throws {
```
Comment (mna) [inline Sources/Socket.swift]: This is the only method that changed.

**Comment by billabt** [comment]
The `init` method was _optional_ as was the `path` parameter originally when it was originally created because at that time, it did return `nil` and the `path` was a truly optional parameter.  It hasn't been changed primarily for _backward compatibility_.  At some point (probably when I update for **Swift 4**), I'll make these and some other interface changes.  In the meantime, I'll merge your PR as soon as Travis completes.  Thanks for PR.

**Comment by mna** [comment]
Makes sense, thanks!

**Comment by davidgyoung** [comment]
Thanks @mna, I can confirm unix sockets work for me now.
